version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itau-api
    ports:
      - "8080:8080"
    environment:
      - STATS_WINDOW_SECONDS=60  # Janela de tempo para estatísticas
      - LOG_LEVEL=info          # Nível de log (debug, info, warn, error)
      - PORT=8080               # Porta da API
      - HOST=0.0.0.0           # Host da API
      - ENVIRONMENT=production  # Ambiente (development, production)
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs  # Mount logs directory
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
